version: 2

models:
    - name: tripdata_full
      description: "A starter dbt model"
      columns:
          - name: tripID
            tests:
                - not_null
          - name: vendorID
            tests:
                - not_null
          - name: PULocationID
            tests:
                - not_null
